//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHT.Infrastructure.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class prizesDiscounts
    {
        public long id { get; set; }
        public long configId { get; set; }
        public string typeDiscount { get; set; }
        public string discountValue { get; set; }
    
        public virtual prizesConfig prizesConfig { get; set; }
    }
}
